"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os
import urllib.parse
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# On Railway, this MUST be set via environment variables for security
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if os.getenv('ENVIRONMENT') == 'production':
        raise ValueError('SECRET_KEY environment variable is required in production')
    # Development fallback only
    SECRET_KEY = 'django-insecure-dev-key-only-for-local-development'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
# For Railway: add *.railway.app to your ALLOWED_HOSTS environment variable


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'axes',  # Brute-force protection
    'django_ratelimit',  # Rate limiting

    # Local apps
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',  # Must come after AuthenticationMiddleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

AUTH_USER_MODEL = 'api.User'

# ========== Authentication & Security ==========
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # django-axes 5.0+ (brute-force protection)
    'django.contrib.auth.backends.ModelBackend',
]

# ========== Caching Configuration ==========
# Production: Use Redis (Railway, Render, Fly.io provide REDIS_URL)
# Development: Falls back to LocMemCache (not production-safe)
REDIS_URL = os.environ.get('REDIS_URL')

if REDIS_URL:
    # Production: Redis cache
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'redis.StrictRedis',
                'CONNECTION_POOL_KWARGS': {
                    'socket_connect_timeout': 5,
                    'socket_keepalive': True,
                    'socket_keepalive_options': {
                        1: 1,
                        2: 3,
                        3: 5,
                    } if hasattr(__builtins__, 'TCP_KEEPIDLE') else {},
                    'retry_on_timeout': True,
                },
            },
            'KEY_PREFIX': 'academy',
            'TIMEOUT': 300,
        }
    }
else:
    # Development/Fallback: Local memory cache
    # WARNING: Not suitable for production or distributed environments
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
            'TIMEOUT': 300,
        }
    }

# ========== Django-Axes Configuration (Brute-force Protection) ==========
AXES_FAILURE_LIMIT = 5  # Lock after 5 failed attempts
AXES_COOLOFF_DURATION = timedelta(minutes=15)  # Lock duration
AXES_LOCK_OUT_AT_FAILURE = True
AXES_USE_USER_AGENT = False  # Deprecated; removed in django-axes 5.0+
AXES_LOCKOUT_TEMPLATE = None  # Use default

# Use cache backend for storing failed attempts
AXES_CACHE = 'default'

# ========== Django-Ratelimit Configuration ==========
# Uses the CACHES['default'] backend (Redis in production)
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_ENABLE = True

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Replicate database logic from server.ts
db_url = os.environ.get('DATABASE_URL') or os.environ.get('POSTGRES_URL') or os.environ.get('PGURL')

if not db_url and os.environ.get('DB_HOST') and os.environ.get('DB_USER') and os.environ.get('DB_PASSWORD'):
    port = os.environ.get('DB_PORT', '5432')
    name = os.environ.get('DB_NAME', 'postgres')
    encoded_user = urllib.parse.quote(os.environ.get('DB_USER', ''))
    encoded_pass = urllib.parse.quote(os.environ.get('DB_PASSWORD', ''))
    host = os.environ.get('DB_HOST', '')
    db_url = f"postgres://{encoded_user}:{encoded_pass}@{host}:{port}/{name}"

if db_url:
    # Use Postgres
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(db_url, conn_max_age=600, conn_health_checks=True)
    }
else:
    # Fallback to local SQLite if no config provided
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/assets/'
MEDIA_URL = '/media/'
STATICFILES_DIRS = [
    BASE_DIR / 'dist' / 'assets',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ========== System Checks - Suppress when falling back to LocMemCache ==========
# Only use this if Redis is truly unavailable AND you accept the production risks
if not REDIS_URL:
    SILENCED_SYSTEM_CHECKS = [
        'django_ratelimit.E003',  # LocMemCache not shared
        'django_ratelimit.W001',  # LocMemCache not officially supported
    ]
